/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  // Enable JIT mode for better performance
  mode: 'jit',
  theme: {
    extend: {
      colors: {
        glass: {
          50: "rgba(255, 255, 255, 0.1)",
          100: "rgba(255, 255, 255, 0.2)",
          200: "rgba(255, 255, 255, 0.3)",
          300: "rgba(255, 255, 255, 0.4)",
          500: "rgba(255, 255, 255, 0.6)",
          700: "rgba(255, 255, 255, 0.8)",
          900: "rgba(255, 255, 255, 0.9)",
        },
        dark: {
          50: "rgba(0, 0, 0, 0.1)",
          100: "rgba(0, 0, 0, 0.2)",
          200: "rgba(0, 0, 0, 0.3)",
          300: "rgba(0, 0, 0, 0.4)",
          500: "rgba(0, 0, 0, 0.6)",
          700: "rgba(0, 0, 0, 0.8)",
          900: "rgba(0, 0, 0, 0.9)",
        },
      },
      backdropBlur: {
        xs: "2px",
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
      },
      // Optimized animations with hardware acceleration
      animation: {
        "fade-in": "fadeIn 0.3s ease-in-out",
        "slide-up": "slideUp 0.3s ease-out",
        "slide-down": "slideDown 0.3s ease-out",
        "scale-in": "scaleIn 0.2s ease-out",
        "pulse-glow": "pulseGlow 3s ease-in-out infinite",
        float: "float 8s ease-in-out infinite",
        "floating-optimized": "floatingOptimized 6s ease-in-out infinite",
      },
      // Optimized keyframes with hardware acceleration
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0", transform: "translateZ(0)" },
          "100%": { opacity: "1", transform: "translateZ(0)" },
        },
        slideUp: {
          "0%": { transform: "translateY(20px) translateZ(0)", opacity: "0" },
          "100%": { transform: "translateY(0) translateZ(0)", opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-20px) translateZ(0)", opacity: "0" },
          "100%": { transform: "translateY(0) translateZ(0)", opacity: "1" },
        },
        scaleIn: {
          "0%": { transform: "scale(0.95) translateZ(0)", opacity: "0" },
          "100%": { transform: "scale(1) translateZ(0)", opacity: "1" },
        },
        pulseGlow: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(59, 130, 246, 0.4)", transform: "translateZ(0)" },
          "50%": { boxShadow: "0 0 30px rgba(59, 130, 246, 0.6)", transform: "translateZ(0)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px) translateZ(0)" },
          "50%": { transform: "translateY(-8px) translateZ(0)" },
        },
        floatingOptimized: {
          "0%, 100%": { transform: "translateY(0px) translateZ(0)" },
          "50%": { transform: "translateY(-6px) translateZ(0)" },
        },
      },
    },
  },
  plugins: [],
  // Performance optimizations
  corePlugins: {
    // Disable unused core plugins to reduce CSS size
    preflight: true,
    container: false,
    accessibility: false,
    appearance: false,
    backgroundAttachment: false,
    backgroundClip: true,
    backgroundColor: true,
    backgroundImage: true,
    gradientColorStops: true,
    backgroundOpacity: true,
    backgroundPosition: true,
    backgroundRepeat: false,
    backgroundSize: true,
    borderCollapse: false,
    borderColor: true,
    borderOpacity: true,
    borderRadius: true,
    borderStyle: true,
    borderWidth: true,
    boxSizing: true,
    cursor: true,
    display: true,
    divideColor: false,
    divideOpacity: false,
    divideStyle: false,
    divideWidth: false,
    fill: false,
    flex: true,
    flexDirection: true,
    flexGrow: true,
    flexShrink: true,
    flexWrap: true,
    float: false,
    clear: false,
    fontFamily: true,
    fontSize: true,
    fontSmoothing: true,
    fontStyle: false,
    fontWeight: true,
    height: true,
    inset: true,
    justifyContent: true,
    justifyItems: false,
    justifySelf: false,
    letterSpacing: true,
    lineHeight: true,
    listStylePosition: false,
    listStyleType: false,
    margin: true,
    maxHeight: true,
    maxWidth: true,
    minHeight: true,
    minWidth: true,
    objectFit: false,
    objectPosition: false,
    opacity: true,
    order: false,
    outline: true,
    overflow: true,
    overscrollBehavior: false,
    padding: true,
    placeContent: false,
    placeItems: false,
    placeSelf: false,
    placeholderColor: true,
    placeholderOpacity: true,
    pointerEvents: true,
    position: true,
    resize: false,
    space: true,
    stroke: false,
    strokeWidth: false,
    tableLayout: false,
    textAlign: true,
    textColor: true,
    textOpacity: true,
    textOverflow: true,
    textTransform: false,
    textDecoration: true,
    textDecorationColor: false,
    textDecorationStyle: false,
    textDecorationThickness: false,
    textUnderlineOffset: false,
    textIndent: false,
    verticalAlign: false,
    visibility: true,
    whitespace: true,
    width: true,
    wordBreak: false,
    zIndex: true,
    gap: true,
    gridAutoFlow: false,
    gridTemplateColumns: false,
    gridAutoColumns: false,
    gridColumn: false,
    gridColumnStart: false,
    gridColumnEnd: false,
    gridTemplateRows: false,
    gridAutoRows: false,
    gridRow: false,
    gridRowStart: false,
    gridRowEnd: false,
    transform: true,
    transformOrigin: false,
    scale: true,
    rotate: true,
    translate: true,
    skew: false,
    transitionProperty: true,
    transitionDelay: true,
    transitionDuration: true,
    transitionTimingFunction: true,
    animation: true,
  },
}
